### ISSUE TITLE
Adding more python packages isn't working

### ISSUE THREAD

**Issue by guilhermenoronha** [bitnami/bitnami-docker-jupyter-base-notebook#2]
### Name and Version

bitnami/jupyter-base-notebook

### What steps will reproduce the bug?

Create Dockerfile and add the following code:

```
FROM bitnami/jupyter-base-notebook:latest

RUN conda install --quiet --yes \
    'pyspark' && \
    conda clean --all -f -y
```
Run this command in terminal: `sudo docker build --rm -t jupyter-spark .`

I'm doing something wrong? Thanks in advance for any support.

### What is the expected behavior?

I expected to create an extensible container with the packages I wanted.

### What do you see instead?

Output: 
```
EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: /opt/bitnami/miniconda
  uid: 1001
  gid: 0
```

### Additional information

Docker Version: 20.10.13, build a224086
OS: Linux ATHENA-LINUX 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Version of Container: latest

**Comment by carrodher** [comment]
You need to change the user but at _Dockerfile_ level:
```Dockerfile
FROM bitnami/jupyter-base-notebook:latest
USER root
RUN conda install --quiet --yes \
    'pyspark' && \
    conda clean --all -f -y
USER 1001
```

I will update the README, thanks.

**Comment by guilhermenoronha** [comment]
> You need to change the user but at _Dockerfile_ level:
> 
> ```dockerfile
> FROM bitnami/jupyter-base-notebook:latest
> USER root
> RUN conda install --quiet --yes \
>     'pyspark' && \
>     conda clean --all -f -y
> USER 1001
> ```
> 
> I will update the README, thanks.

It worked. Thank you.

**Comment by OneCricketeer** [comment]
(Py)Spark requires Java to be installed, as well, by the way. I'm not sure if conda will do this for you.
